### ISSUE TITLE
Calling bash-simple / bash-simple-plus without arguments results in $# counting 1 empty argument

### ISSUE THREAD

**Issue by branb** [xwmx/bash-boilerplate#3]
When I pull the latest version and place the following code into the simple function:

`
 printf "Argument count: $#, arguments:\n"
  for arg in "$@"; do
    printf " - $arg\n"
  done
`

and execute the script without arguments like this:

`./bash-simple`

then the output is:

`Argument count: 1, arguments:
 -`

Somehow, there is an empty string registered as our first argument.

Replacing the main call at the bottom of the script:

`_main "${@:-}"`

with:

`_main "$@"`

though, yields the expected output:

`Argument count: 0, arguments:`

Is there a reason why `${@:-}` instead of `$@` has been used?

I've created two test scripts that just contain the code in question, one with the [correct output](https://gist.github.com/branb/d81f3f25c06b1319a4fd1f6fde4d70dd) and one with the [wrong output](https://gist.github.com/branb/8908a7fe5c55ca4cd7369595d6c148bd).

**Comment by xwmx** [comment]
Good catch. The `"${@:-}"` construct, using parameter expansion to provide a default blank string when `$@` is empty, was introduced in cd2a983 in order to avoid unbound variable errors in older bash versions, specifically the default Bash 3.2 on macOS. This was an incorrect solution, as you noted. I've updated these scripts to pass the variables with just `"$@"`, which appears to be error-free in both 3.2 and 4.4. Thanks for the heads up!
